const Apmc_names = {
  map: {
      AABU_ROAD: { name: 'AABU_ROAD', hindiName: 'आबू रोड' },
      AJMER_F_AND_V: { name: 'AJMER_F_AND_V', hindiName: 'अजमेर फल और सब्जी मंडी' },
      ALWAR: { name: 'ALWAR', hindiName: 'अलवर' },
      ANOOPGARH: { name: 'ANOOPGARH', hindiName: 'अनूपगढ़' },
      ANTA: { name: 'ANTA', hindiName: 'अन्ता' },
      ATRU: { name: 'ATRU', hindiName: 'आत्रू' },
      BAJJU: { name: 'BAJJU', hindiName: 'बज्जू' },
      BALOTRA: { name: 'BALOTRA', hindiName: 'बालोतरा' },
      BANDIKUI: { name: 'BANDIKUI', hindiName: 'बांदीकुई' },
      BARAN: { name: 'BARAN', hindiName: 'बारां' },
      BARISADRI: { name: 'BARISADRI', hindiName: 'बड़ीसादड़ी' },
      BARMER: { name: 'BARMER', hindiName: 'बाड़मेर' },
      BARODAMEV: { name: 'BARODAMEV', hindiName: 'बरोड़ामेव' },
      BASSI: { name: 'BASSI', hindiName: 'बसी' },
      BAYANA: { name: 'BAYANA', hindiName: 'बयाना' },
      BEAWAR: { name: 'BEAWAR', hindiName: 'ब्यावर' },
      BEGU: { name: 'BEGU', hindiName: 'बेगूं' },
      BHADRA: { name: 'BHADRA', hindiName: 'भादरा' },
      BHAGAT_KI_KOTHI: { name: 'BHAGAT_KI_KOTHI', hindiName: 'भगत की कोठी' },
      BHARATPUR: { name: 'BHARATPUR', hindiName: 'भरतपुर' },
      BHAWANI_MANDI: { name: 'BHAWANI_MANDI', hindiName: 'भवानी मंडी' },
      BHILWARA: { name: 'BHILWARA', hindiName: 'भीलवाड़ा' },
      BHINMAL: { name: 'BHINMAL', hindiName: 'भीनमाल' },
      BIJAY_NAGAR: { name: 'BIJAY_NAGAR', hindiName: 'बिजयनगर' },
      BIKANER_F_AND_V: { name: 'BIKANER_F_AND_V', hindiName: 'बीकानेर फल और सब्जी मंडी' },
      BIKANER_GRAIN: { name: 'BIKANER_GRAIN', hindiName: 'बीकानेर अनाज मंडी' },
      BILARA: { name: 'BILARA', hindiName: 'बिलाड़ा' },
      BIJOLIYA: { name: 'BIJOLIYA', hindiName: 'बिजोलिया' },
      BUNDI: { name: 'BUNDI', hindiName: 'बूंदी' },
      CHABRA: { name: 'CHABRA', hindiName: 'छबड़ा' },
      CHAKSU: { name: 'CHAKSU', hindiName: 'चाकसू' },
      CHIRAWA: { name: 'CHIRAWA', hindiName: 'चिड़ावा' },
      CHITTORGARH: { name: 'CHITTORGARH', hindiName: 'चित्तौड़गढ' },
      CHOTTISADRI: { name: 'CHOTTISADRI', hindiName: 'छोटी सादड़ी' },
      CHOMEHLA: { name: 'CHOMEHLA', hindiName: 'चोमेला' },
      CHOMU_F_AND_V: { name: 'CHOMU_F_AND_V', hindiName: 'चोमू फल और सब्जी मंडी' },
      CHOMU_GRAIN: { name: 'CHOMU_GRAIN', hindiName: 'चोमू अनाज मंडी' },
      CHURU: { name: 'CHURU', hindiName: 'चूरू' },
      DAUSA: { name: 'DAUSA', hindiName: 'दौसा' },
      DEEDWANA: { name: 'DEEDWANA', hindiName: 'डीडवाना' },
      DEEG: { name: 'DEEG', hindiName: 'डीग' },
      DEGANA: { name: 'DEGANA', hindiName: 'डेगाना' },
      DEI: { name: 'DEI', hindiName: 'देई' },
      DEOLI: { name: 'DEOLI', hindiName: 'देवली' },
      DHOLPUR: { name: 'DHOLPUR', hindiName: 'धौलपुर' },
      DOONI: { name: 'DOONI', hindiName: 'डूनी' },
      DUNGARPUR: { name: 'DUNGARPUR', hindiName: 'डूंगरपुर' },
      FATEHNAGAR: { name: 'FATEHNAGAR', hindiName: 'फतेहनगर' },
      FATEHPUR: { name: 'FATEHPUR', hindiName: 'फतेहपुर' },
      GAJSINGHPUR: { name: 'GAJSINGHPUR', hindiName: 'गजसिंहपुर' },
      GANGAPUR_CITY: { name: 'GANGAPUR_CITY', hindiName: 'गंगापुर सिटी' },
      GHARSANA: { name: 'GHARSANA', hindiName: 'घड़साना' },
      GOLUWALA: { name: 'GOLUWALA', hindiName: 'गोलुवाला' },
      GUDA_GODJI: { name: 'GUDA_GODJI', hindiName: 'गुड़ा गोडजी' },
      HANUMANGARH: { name: 'HANUMANGARH', hindiName: 'हनुमानगढ़' },
      HANUMANGARH_TOWN: { name: 'HANUMANGARH_TOWN', hindiName: 'हनुमानगढ़ टाउन' },
      HINDOUN: { name: 'HINDOUN', hindiName: 'हिण्डौन' },
      IKLERA: { name: 'IKLERA', hindiName: 'इकलेरा' },
      ITAWA: { name: 'ITAWA', hindiName: 'इटावा' },
      JAIPUR_F_AND_V_MUHANA: { name: 'JAIPUR_F_AND_V_MUHANA', hindiName: 'जयपुर फल और सब्जी मंडी मुहाना' },
      JAIPUR_GRAIN: { name: 'JAIPUR_GRAIN', hindiName: 'जयपुर अनाज मंडी' },
      JAITARAN: { name: 'JAITARAN', hindiName: 'जैतारण' },
      JAITSAR: { name: 'JAITSAR', hindiName: 'जैसार' },
      JALORE: { name: 'JALORE', hindiName: 'जालोर' },
      JHALRAPATAN: { name: 'JHALRAPATAN', hindiName: 'झालरापाटन' },
      JHUNJHUNU: { name: 'JHUNJHUNU', hindiName: 'झुंझुनू' },
      JODHPUR_F_AND_V: { name: 'JODHPUR_F_AND_V', hindiName: 'जोधपुर फल और सब्जी मंडी' },
      JODHPUR_GRAIN: { name: 'JODHPUR_GRAIN', hindiName: 'जोधपुर अनाज मंडी' },
      KAPASAN: { name: 'KAPASAN', hindiName: 'कपासन' },
      KEKRI: { name: 'KEKRI', hindiName: 'केकड़ी' },
      KESRISINGHPUR: { name: 'KESRISINGHPUR', hindiName: 'केसरसिंहपुर' },
      KHAIRTHAL: { name: 'KHAIRTHAL', hindiName: 'खैरथल' },
      KHAJUWALA: { name: 'KHAJUWALA', hindiName: 'खाजूवाला' },
      KHANPUR: { name: 'KHANPUR', hindiName: 'खानपुर' },
      KHERLI: { name: 'KHERLI', hindiName: 'खैरली' },
      KISHANGARH_RENWAL: { name: 'KISHANGARH_RENWAL', hindiName: 'किशनगढ़ रेनवाल' },
      KOTA: { name: 'KOTA', hindiName: 'कोटा' },
      KOTA_F_AND_V: { name: 'KOTA_F_AND_V', hindiName: 'कोटा फल और सब्जी मंडी' },
      KOTPUTLI: { name: 'KOTPUTLI', hindiName: 'कोटपूतली' },
      KUCHAMANCITY: { name: 'KUCHAMANCITY', hindiName: 'कुचामन सिटी' },
      LALSOT: { name: 'LALSOT', hindiName: 'लालसोट' },
      LOONKARANSAR: { name: 'LOONKARANSAR', hindiName: 'लूणकरनसर' },
      M_KISHANGARH: { name: 'M_KISHANGARH', hindiName: 'मदन किशनगढ़' },
      MAHUWA_MANDAWAR: { name: 'MAHUWA_MANDAWAR', hindiName: 'महुंवा मंडावर' },
      MAHUWA_RJ: { name: 'MAHUWA_RJ', hindiName: 'महुंवा' },
      MALPURA: { name: 'MALPURA', hindiName: 'मालपुरा' },
      MANDAWARI: { name: 'MANDAWARI', hindiName: 'मंडावरी' },
      MERTA_CITY: { name: 'MERTA_CITY', hindiName: 'मेड़ता सिटी' },
      NADBAI: { name: 'NADBAI', hindiName: 'नदबई' },
      NAGAR: { name: 'NAGAR', hindiName: 'नगर' },
      NAGOUR: { name: 'NAGOUR', hindiName: 'नागौर' },
      NAWALGARH: { name: 'NAWALGARH', hindiName: 'नवलगढ़' },
      NIMBAHERA: { name: 'NIMBAHERA', hindiName: 'निंबाहेड़ा' },
      NIWAI: { name: 'NIWAI', hindiName: 'निवाई' },
      NOHAR: { name: 'NOHAR', hindiName: 'नोहर' },
      NOKHA: { name: 'NOKHA', hindiName: 'नोखा' },
      PADAMPUR: { name: 'PADAMPUR', hindiName: 'पदमपुर' },
      PALI: { name: 'PALI', hindiName: 'पाली' },
      PALSANA: { name: 'PALSANA', hindiName: 'पालसाना' },
      PHALODI: { name: 'PHALODI', hindiName: 'फलोदी' },
      PILIBANGA: { name: 'PILIBANGA', hindiName: 'पिलिबंगा' },
      PIPARCITY: { name: 'PIPARCITY', hindiName: 'पिपार सिटी' },
      PRATAPGARH_RJ: { name: 'PRATAPGARH_RJ', hindiName: 'प्रतापगढ़' },
      RAISINGHNAGAR: { name: 'RAISINGHNAGAR', hindiName: 'रायसिंहनगर' },
      RAJDHANI_MANDI_KUKARKHERA: { name: 'RAJDHANI_MANDI_KUKARKHERA', hindiName: 'राजधानी मंडी कूकड़खेड़ा' },
      RAJSAMAND: { name: 'RAJSAMAND', hindiName: 'राजसमंद' },
      RAMGANJ_MANDI: { name: 'RAMGANJ_MANDI', hindiName: 'रामगंज मंडी' },
      RIDMALSAR: { name: 'RIDMALSAR', hindiName: 'रिड़मलसर' },
      RANI: { name: 'RANI', hindiName: 'रानी' },
      RANIWARA: { name: 'RANIWARA', hindiName: 'रानीवाड़ा' },
      RAWATSAR: { name: 'RAWATSAR', hindiName: 'रावतसर' },
      RAWLA: { name: 'RAWLA', hindiName: 'रावला' },
      SADULPUR: { name: 'SADULPUR', hindiName: 'सादुलपुर' },
      SADULSHAHAR: { name: 'SADULSHAHAR', hindiName: 'सादुलशहर' },
      SANGARIYA: { name: 'SANGARIYA', hindiName: 'संगरिया' },
      SARDAR_SHAHAR: { name: 'SARDAR_SHAHAR', hindiName: 'सरदार शहर' },
      SAWAI_MADHOPUR: { name: 'SAWAI_MADHOPUR', hindiName: 'सवाई माधोपुर' },
      SHAHPURA: { name: 'SHAHPURA', hindiName: 'शाहपुरा' },
      SIKAR: { name: 'SIKAR', hindiName: 'सीकर' },
      SOJAT_ROAD: { name: 'SOJAT_ROAD', hindiName: 'सोजत रोड' },
      SRI_DUNGARGARH: { name: 'SRI_DUNGARGARH', hindiName: 'श्री डूंगरगढ़' },
      SRI_GANGANAGAR_GRAIN: { name: 'SRI_GANGANAGAR_GRAIN', hindiName: 'श्री गंगानगर अनाज मंडी' },
      SRI_MADHOPUR: { name: 'SRI_MADHOPUR', hindiName: 'श्री माधोपुर' },
      SRI_VIJAYNAGAR: { name: 'SRI_VIJAYNAGAR', hindiName: 'श्री विजयनगर' },
      SRIGANGANAGAR_F_AND_V: { name: 'SRIGANGANAGAR_F_AND_V', hindiName: 'श्रीगंगानगर फल और सब्जी मंडी' },
      SRIKARANPUR: { name: 'SRIKARANPUR', hindiName: 'श्रीकरणपुर' },
      SUJANGARH: { name: 'SUJANGARH', hindiName: 'सुजानगढ़' },
      SUMERPUR: { name: 'SUMERPUR', hindiName: 'सुमेरपुर' },
      SUMERGANJ: { name: 'SUMERGANJ', hindiName: 'सुमेरगंज' },
      SURATGARH: { name: 'SURATGARH', hindiName: 'सूरतगढ़' },
      SURAJGARH: { name: 'SURAJGARH', hindiName: 'सूरजगढ़' },
      TONK: { name: 'TONK', hindiName: 'टोंक' },
      UDAIPUR_F_AND_V: { name: 'UDAIPUR_F_AND_V', hindiName: 'उदयपुर फल और सब्जी मंडी' },
      UDAIPUR_GRAIN: { name: 'UDAIPUR_GRAIN', hindiName: 'उदयपुर अनाज मंडी' },
      UNIYARA: { name: 'UNIYARA', hindiName: 'उनियारा' },
      SANCHORE: { name: 'SANCHORE', hindiName: 'सांचोर' },
      AJMER_GRAIN: { name: 'AJMER_GRAIN', hindiName: 'अजमेर अनाज' },
      BANSWARA: { name: 'BANSWARA', hindiName: 'बांसवाड़ा' },
      GANGAPUR_RJ: { name: 'GANGAPUR_RJ', hindiName: 'गंगापुर राज.' },
      JAISALMER: { name: 'JAISALMER', hindiName: 'जैसलमेर' },
      KAMAN: { name: 'KAMAN', hindiName: 'कमान' },
      MANDALGARH: { name: 'MANDALGARH', hindiName: 'मांडलगढ़' },
      NEEM_KA_THANA: { name: 'NEEM_KA_THANA', hindiName: 'नीम का थाना' },
      RATANGARH: { name: 'RATANGARH', hindiName: 'रतनगढ़' },
      KESHORAIPATAN: { name: 'KESHORAIPATAN', hindiName: 'केशवराय पाटन' },
      BEHROR: { name: 'BEHROR', hindiName: 'बहरोड़' },
      JAYAL: { name: 'JAYAL', hindiName: 'जायल' },
      KHANDAR: { name: 'KHANDAR', hindiName: 'खण्डार' },
      MANOHAR_THANA: { name: 'MANOHAR_THANA', hindiName: 'मनोहरथाना' },
      MOHANGARH: { name: 'MOHANGARH', hindiName: 'मोहनगढ़' },
      NAHARGARH: { name: 'NAHARGARH', hindiName: 'नाहरगढ़' },
      OSIAN_MATHANIA: { name: 'OSIAN_MATHANIA', hindiName: 'ओसियां ​​मथानिया' },
      SAMRANIA: { name: 'SAMRANIA', hindiName: 'समरनिया' },
      TIJARA: { name: 'TIJARA', hindiName: 'तिजारा' },
  },
  fromNormalizedValue: (value) => {
      const normalizedValue = value
          .toUpperCase()
          .replaceAll(/[\s\-\.\(\)]/g, '_')
          .replaceAll(/\/+/g, '_')
          .replaceAll(/_+/g, '_')
          .replaceAll(/^_|_$/g, '')
          .replaceAll('PSYLLIUM', 'PS_YLLIUM');
      return Apmc_names.map[normalizedValue] || null;
  },
};

const Commodities_names = {
  map: {
      APPLE: { name: 'APPLE', hindiName: 'सेब' },
      AMLA: { name: 'AMLA', hindiName: 'आंवला' },
      BANANA: { name: 'BANANA', hindiName: 'केला' },
      BEANS_CLUSTER: { name: 'BEANS_CLUSTER', hindiName: 'गवार फली' },
      BITTER_GOURD: { name: 'BITTER_GOURD', hindiName: 'करेला' },
      BOTTLE_GOURD: { name: 'BOTTLE_GOURD', hindiName: 'लौकी' },
      BRINJAL: { name: 'BRINJAL', hindiName: 'बैंगन' },
      CABBAGE: { name: 'CABBAGE', hindiName: 'पत्तागोभी' },
      CAULIFLOWER: { name: 'CAULIFLOWER', hindiName: 'फूलगोभी' },
      CHILLIES: { name: 'CHILLIES', hindiName: 'मिर्च' },
      CORIANDAR: { name: 'CORIANDAR', hindiName: 'धनिया' },
      CUCUMBER: { name: 'CUCUMBER', hindiName: 'खीरा' },
      FENUGREEK_HARI_METHI: { name: 'FENUGREEK_HARI_METHI', hindiName: 'हरी मेथी' },
      LADY_FINGER: { name: 'LADY_FINGER', hindiName: 'भिंडी' },
      LEMON: { name: 'LEMON', hindiName: 'नींबू' },
      MARI_GOLD: { name: 'MARI_GOLD', hindiName: 'गेंदे का फूल' },
      MINT_LEAVES: { name: 'MINT_LEAVES', hindiName: 'पुदीने के पत्ते' },
      MOUSAMBI: { name: 'MOUSAMBI', hindiName: 'मौसंबी' },
      ONION: { name: 'ONION', hindiName: 'प्याज' },
      ORANGE: { name: 'ORANGE', hindiName: 'संतरा' },
      PAPAYA: { name: 'PAPAYA', hindiName: 'पपीता' },
      POTATO: { name: 'POTATO', hindiName: 'आलू' },
      PUMPKIN: { name: 'PUMPKIN', hindiName: 'कद्दू' },
      RADDISH: { name: 'RADDISH', hindiName: 'मूली' },
      RIDGE_GOURD_TURAI: { name: 'RIDGE_GOURD_TURAI', hindiName: 'तुरई' },
      SPINACH_PALAK: { name: 'SPINACH_PALAK', hindiName: 'पालक' },
      SPRING_ONION: { name: 'SPRING_ONION', hindiName: 'हरा प्याज' },
      TINDA: { name: 'TINDA', hindiName: 'टिंडा' },
      TOMATO: { name: 'TOMATO', hindiName: 'टमाटर' },
      TAPIOCA: { name: 'TAPIOCA', hindiName: 'टैपिओका' },
      POMEGRANATE: { name: 'POMEGRANATE', hindiName: 'अनार' },
      PEAS_GREEN: { name: 'PEAS_GREEN', hindiName: 'हरा मटर' },
      PINE_APPLE: { name: 'PINE_APPLE', hindiName: 'अनानास' },
      SWEET_LEMON_MOSAMBI: { name: 'SWEET_LEMON_MOSAMBI', hindiName: 'मौसंबी' },
      WATER_MELON: { name: 'WATER_MELON', hindiName: 'तरबूज' },
      TURMERIC_ATTU: { name: 'TURMERIC_ATTU', hindiName: 'हल्दी अट्टू' },
      GRAPES: { name: 'GRAPES', hindiName: 'अंगूर' },
      GUAVA: { name: 'GUAVA', hindiName: 'अमरूद' },
      KINNOW: { name: 'KINNOW', hindiName: 'किन्नू' },
      GARLIC: { name: 'GARLIC', hindiName: 'लहसुन' },
      GINGER: { name: 'GINGER', hindiName: 'अदरक' },
      GREEN_CHILLI: { name: 'GREEN_CHILLI', hindiName: 'हरी मिर्च' },
      CORIANDER_LEAVES: { name: 'CORIANDER_LEAVES', hindiName: 'धनिया पत्ते' },
      CORIANDER: { name: 'CORIANDER', hindiName: 'धनिया' },
      CHIKOOS: { name: 'CHIKOOS', hindiName: 'चीकू' },
      CAPSICUM: { name: 'CAPSICUM', hindiName: 'शिमला मिर्च' },
      CARROT: { name: 'CARROT', hindiName: 'गाजर' },
      ARBI_COLACASIA: { name: 'ARBI_COLACASIA', hindiName: 'अरबी' },
      BARLEY_JAU: { name: 'BARLEY_JAU', hindiName: 'जौ' },
      BAJRA: { name: 'BAJRA', hindiName: 'बाजरा' },
      COTTON: { name: 'COTTON', hindiName: 'कपास' },
      GUAR_SEEDS: { name: 'GUAR_SEEDS', hindiName: 'ग्वार बीज' },
      WHEAT: { name: 'WHEAT', hindiName: 'गेहूं' },
      MUSTARD: { name: 'MUSTARD', hindiName: 'सरसों' },
      SESAME_SEED: { name: 'SESAME_SEED', hindiName: 'तिल' },
      PADDY: { name: 'PADDY', hindiName: 'धान' },
      MOONG_WHOLE_GREEN_GRAM: { name: 'MOONG_WHOLE_GREEN_GRAM', hindiName: 'मूंग साबुत' },
      CORIANDER_WHOLE: { name: 'CORIANDER_WHOLE', hindiName: 'धनिया साबुत' },
      CHANA_BENGAL_GRAM: { name: 'CHANA_BENGAL_GRAM', hindiName: 'चना' },
      SOYA_YELLOW: { name: 'SOYA_YELLOW', hindiName: 'सोया पीला' },
      SOYABEANS: { name: 'SOYABEANS', hindiName: 'सोयाबीन' },
      URAD_BLACK_GRAM: { name: 'URAD_BLACK_GRAM', hindiName: 'उड़द' },
      MAIZE: { name: 'MAIZE', hindiName: 'मक्का' },
      ISABGOL: { name: 'ISABGOL', hindiName: 'इसबगोल' },
      MOTH: { name: 'MOTH', hindiName: 'मोट' },
      CHANA_BENGAL_GRAM_DESI: { name: 'CHANA_BENGAL_GRAM_DESI', hindiName: 'चना देसी' },
      MAIZE_COMMON: { name: 'MAIZE_COMMON', hindiName: 'मक्का सामान्य' },
      FENUGREEK_WHOLE: { name: 'FENUGREEK_WHOLE', hindiName: 'मेथी साबुत' },
      GROUND_NUT: { name: 'GROUND_NUT', hindiName: 'मूंगफली' },
      COCONUT_DEHUSKED_IN_QUINTAL: { name: 'COCONUT_DEHUSKED_IN_QUINTAL', hindiName: 'नारियल (छिले हुए)' },
      CHILLI_NS_250_BULLET: { name: 'CHILLI_NS_250_BULLET', hindiName: 'मिर्ची बुलेट' },
      POMEGRANATE_BHAGAWA: { name: 'POMEGRANATE_BHAGAWA', hindiName: 'अनार भगवा' },
      PEAR: { name: 'PEAR', hindiName: 'नाशपाती' },
      GROUND_NUT_NEW: { name: 'GROUND_NUT_NEW', hindiName: 'नई मूंगफली' },
      TARAMIRA: { name: 'TARAMIRA', hindiName: 'तारामीरा' },
      SOUNF: { name: 'SOUNF', hindiName: 'सौंफ' },
      MUSTARD_SEED: { name: 'MUSTARD_SEED', hindiName: 'सरसों का बीज' },
      MUSTARD_LEAF: { name: 'MUSTARD_LEAF', hindiName: 'सरसों का पत्ता' },
      JOWAR: { name: 'JOWAR', hindiName: 'ज्वार' },
      GREEN_GRAM: { name: 'GREEN_GRAM', hindiName: 'हरा चना' },
      CUMMIN: { name: 'CUMMIN', hindiName: 'जीरा' },
      GRAPEFRUIT: { name: 'GRAPEFRUIT', hindiName: 'अंगूर' },
      MUSK_MELON: { name: 'MUSK_MELON', hindiName: 'खरबूजा' },
      MOONG_WHOLE_CHAMKI: { name: 'MOONG_WHOLE_CHAMKI', hindiName: 'मूंग व्होले चमकि' },
      BHINDI_LADIES_FINGER: { name: 'BHINDI_LADIES_FINGER', hindiName: 'भिंडी' },
      POINTED_GOURD_PARWAL: { name: 'POINTED_GOURD_PARWAL', hindiName: 'परवल' },
      POTATO_SWEET: { name: 'POTATO_SWEET', hindiName: 'शकरकंद' },
      MANGO: { name: 'MANGO', hindiName: 'आम' },
      MANGO_RAW: { name: 'MANGO_RAW', hindiName: 'कच्चा आम' },
      IVY_GOURD_KUNDRU: { name: 'IVY_GOURD_KUNDRU', hindiName: 'कुंदरू' },
      KIWI_FRUIT: { name: 'KIWI_FRUIT', hindiName: 'कीवी' },
      GHERKIN: { name: 'GHERKIN', hindiName: 'कच्छा खीरा' },
      BEETROOT: { name: 'BEETROOT', hindiName: 'चुकंदर' },
      COCONUT: { name: 'COCONUT', hindiName: 'नारियल' },
      ISBGOL_PS_YLLIUM_HUSK: { name: 'ISBGOL_PS_YLLIUM_HUSK', hindiName: 'इसबगोल' },
      FENNEL_SEED: { name: 'FENNEL_SEED', hindiName: 'सौंफ' },
      MASOOR: { name: 'MASOOR', hindiName: 'मसूर' },
      SPONGE_GOURD: { name: 'SPONGE_GOURD', hindiName: 'नेनुआ' },
      CHANA_BENGAL_GRAM_SPACE: { name: 'CHANA_BENGAL_GRAM_SPACE', hindiName: 'चना' },
      LOBIA: { name: 'LOBIA', hindiName: 'लोबिया' },
      AMERICAN_COTTON: { name: 'AMERICAN_COTTON', hindiName: 'अमेरिकन कपास' },
      PADDY_COMMON: { name: 'PADDY_COMMON', hindiName: 'धान' },
      CUSTARD_APPLE: { name: 'CUSTARD_APPLE', hindiName: 'सीताफल' },
      SWEET_CORN: { name: 'SWEET_CORN', hindiName: 'मिठा मकई' },
      PLUM: { name: 'PLUM', hindiName: 'आलूबुखारा' },
      ONION_RED: { name: 'ONION_RED', hindiName: 'लाल प्याज' },
      CASTOR_SEED: { name: 'CASTOR_SEED', hindiName: 'अरंडी का बीज' },
      ARHAR_WHOLE_TUR_RED_GRAM: { name: 'ARHAR_WHOLE_TUR_RED_GRAM', hindiName: 'तुअर' },
      MAIZE_YELLOW: { name: 'MAIZE_YELLOW', hindiName: 'पीली मक्का' },
      LOBIA_LOCAL: { name: 'LOBIA_LOCAL', hindiName: 'स्थानीय लोबिया' },
      LINSEED: { name: 'LINSEED', hindiName: 'अलसी' },
      NIGER_SEED: { name: 'NIGER_SEED', hindiName: 'रामतिल' },
      COWPEA_RED: { name: 'COWPEA_RED', hindiName: 'लाल लोबिया' },
      COWPEA_WHITE: { name: 'COWPEA_WHITE', hindiName: 'सफेद लोबिया' },
      PADDY_GRADE_A: { name: 'PADDY_GRADE_A', hindiName: 'ग्रेड ए धान' },
      BOTTLE_GOURDE: { name: 'BOTTLE_GOURDE', hindiName: 'लौकी' },
      COTTON_LOOSE: { name: 'COTTON_LOOSE', hindiName: 'ढीला कपास' },
      SQUASH: { name: 'SQUASH', hindiName: 'स्क्वैश' },
      BER: { name: 'BER', hindiName: 'बेर' },
      APRICOT: { name: 'APRICOT', hindiName: 'खुबानी' },
      BAJRA_HYBRID: { name: 'BAJRA_HYBRID', hindiName: 'हाइब्रिड बाजरा' },
      GROUND_NUT_P_NUT: { name: 'GROUND_NUT_P_NUT', hindiName: 'पीनट' },
      GROUND_NUT_G_2: { name: 'GROUND_NUT_G_2', hindiName: 'जी 2 मूंगफली' },
      GREEN_GRAM_LOCAL: { name: 'GREEN_GRAM_LOCAL', hindiName: 'स्थानीय हरी मटर' },
      HORSE_GRAM_WHOLE: { name: 'HORSE_GRAM_WHOLE', hindiName: 'घोड़ा चना' },
      MAIZE_NEW: { name: 'MAIZE_NEW', hindiName: 'नई मक्का' },
      BROAD_BEANS: { name: 'BROAD_BEANS', hindiName: 'बड़ी फलियां' },
      LOBIA_PODS: { name: 'LOBIA_PODS', hindiName: 'लोबिया की फलियां' },
      TURMERIC: { name: 'TURMERIC', hindiName: 'हल्दी' },
      AJWAIN: { name: 'AJWAIN', hindiName: 'अजवाइन' },
      RICE: { name: 'RICE', hindiName: 'चावल' },
      JIMIKAND_SURAN: { name: 'JIMIKAND_SURAN', hindiName: 'जिमीकंद सूरन' },
      COTTON_RAW: { name: 'COTTON_RAW', hindiName: 'कपास-कच्चा' },
      MAIZE_WHITE: { name: 'MAIZE_WHITE', hindiName: 'मक्का सफेद' },
      PASSION_FRUIT: { name: 'PASSION_FRUIT', hindiName: 'कृष्णकमल फल' },
      WHITE_PEAS: { name: 'WHITE_PEAS', hindiName: 'सफ़ेद मटर' },
      SAL_SEED: { name: 'SAL_SEED', hindiName: 'साल बीज' },
      CHERRY: { name: 'CHERRY', hindiName: 'चेरी' },
      CHANA_GRAM: { name: 'CHANA_GRAM', hindiName: 'चना ग्राम' },
      PADDY_LOCAL: { name: 'PADDY_LOCAL', hindiName: 'धान स्थानीय' },
      GROUND_NUT_PODS: { name: 'GROUND_NUT_PODS', hindiName: 'मूंगफली-फली' },
      BAJRA_LOCAL: { name: 'BAJRA_LOCAL', hindiName: 'बाजरा-स्थानीय' },
      CHILLI_BANGARAM: { name: 'CHILLI_BANGARAM', hindiName: 'मिर्च बंगाराम' },
      CHANA: { name: 'CHANA', hindiName: 'चना' },
      KARBUJA: { name: 'KARBUJA', hindiName: 'करबुजा' },
      BENGAL_GRAM_LOCAL: { name: 'BENGAL_GRAM_LOCAL', hindiName: 'बंगाल ग्राम स्थानीय' },
      MUSTARD_WHITE_SEEDS: { name: 'MUSTARD_WHITE_SEEDS', hindiName: 'सरसों के सफेद बीज' },
      CHIRONJI: { name: 'CHIRONJI', hindiName: 'चिरौंजी' },
      JACK_FRUIT: { name: 'JACK_FRUIT', hindiName: 'जैक फल' },
      BROCCOLI: { name: 'BROCCOLI', hindiName: 'ब्रोकोली' },
      WHEAT_HYBRID: { name: 'WHEAT_HYBRID', hindiName: 'गेहूँ-संकर' },
      CHANA_LOCAL: { name: 'CHANA_LOCAL', hindiName: 'चना-स्थानीय' },
      GINGILY_BLACK: { name: 'GINGILY_BLACK', hindiName: 'गिंगिली (तिल के बीज)-काला' },
      BRINJAL_HYBRID: { name: 'BRINJAL_HYBRID', hindiName: 'बैंगन-संकर' },
      GOLDEN_APPLE_SMALL: { name: 'GOLDEN_APPLE_SMALL', hindiName: 'सुनहरा सेब छोटा' },
      CHANA_BENGAL_GRAM_DOLLAR: { name: 'CHANA_BENGAL_GRAM_DOLLAR', hindiName: 'चना बंगाल ग्राम-डॉलर' },
      SUGAR_SNAP_PEAS: { name: 'SUGAR_SNAP_PEAS', hindiName: 'चीनी स्नैप मटर' },
      JAGGERY: { name: 'JAGGERY', hindiName: 'गुड़' },
      GINGILY_SESAME_SEED_BLACK: { name: 'GINGILY_SESAME_SEED_BLACK', hindiName: 'गिंगिली (तिल के बीज)-काला' },
  },
  fromNormalizedValue: (value) => {
      const normalizedValue = value
          .toUpperCase()
          .replaceAll(/[\s\-\.\(\)]/g, '_')
          .replaceAll(/\/+/g, '_')
          .replaceAll(/_+/g, '_')
          .replaceAll(/^_|_$/g, '')
          .replaceAll('PSYLLIUM', 'PS_YLLIUM');
      return Commodities_names.map[normalizedValue] || null;
  },
};

export { Apmc_names, Commodities_names };
export default { Apmc_names, Commodities_names };